on:
  push:
    branches:
    - main
jobs:
  build_app:
    name: Build preact app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - name: npm install, build
      run: |
        npm install
        npm run build
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v2.0.0
      with:
        path: dist/
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v2.0.3
